package proyecto_n1_generacion_aleatorios;

import static java.lang.Math.pow;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class Interfaz_Principal extends javax.swing.JFrame {
    ArrayList<Integer> Valores = new ArrayList<>();
    ArrayList<Integer> Valores_Cuadrado = new ArrayList<>();
    ArrayList<Integer> Valores_Semillas = new ArrayList<>();
    int tam = 0;
    /**
     * Creates new form Interfaz_Principal
     */
    
    public Interfaz_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_X0 = new javax.swing.JTextField();
        jButton_aditivo1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_cuadrado_medio = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jTextField_Iteraciones = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_m = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_X_1 = new javax.swing.JTextField();
        jButton_aditivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_Limpiar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Ingrese los siguientes datos");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cantidad de iteraciones:");

        jTextField_X0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_X0ActionPerformed(evt);
            }
        });

        jButton_aditivo1.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jButton_aditivo1.setText("Calcular");
        jButton_aditivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aditivo1ActionPerformed(evt);
            }
        });

        jTable_cuadrado_medio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(0, 0, 0), null, null));
        jTable_cuadrado_medio.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        jTable_cuadrado_medio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Iteracion", "Semilla", "Resultado"
            }
        ));
        jTable_cuadrado_medio.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane2.setViewportView(jTable_cuadrado_medio);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("X0");

        jTextField_Iteraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IteracionesActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_aditivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_X0, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Iteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_X0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_Iteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_aditivo1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Método del cuadrado medio", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ingrese los siguientes datos");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("m:");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Valores iniciales");

        jButton_aditivo.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jButton_aditivo.setText("Calcular");
        jButton_aditivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aditivoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Iteración", "Expresión", "Expresión reemplazada", "Resultado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton_Limpiar.setText("Limpiar");
        jButton_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimpiarActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_aditivo, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(41, 41, 41)
                                .addComponent(jTextField_m, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel7)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Limpiar)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField_X_1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel5)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField_X_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_aditivo)
                    .addComponent(jButton_Limpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Método congruencial aditivo", jPanel3);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Slab", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ronald Juárez - Eugenio Pérez - Luis Quintero");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lobster", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Proyecto N1 - Generación de números aleatorios");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_n1_generacion_aleatorios/cubos.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_n1_generacion_aleatorios/dados.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(109, 109, 109))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Método del cuadrado medio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 852, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_X0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_X0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_X0ActionPerformed

    private void jButton_aditivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aditivoActionPerformed
        jTextField_m.setEditable(false);
        jTextField_X_1.setEditable(false);
        int m = 0, valor;
        tam = Valores.size()-1;
        //JOptionPane.showMessageDialog(null,tam);
        boolean band = false;
            String m_text = jTextField_m.getText();
            
            try {
                //Valores.add(Integer.parseInt(X1));
                m = Integer.parseInt(m_text);
            } 
            catch (NumberFormatException e) {
               JOptionPane.showMessageDialog(null,"Error con los valores introducidos");
            }
        int j = 0, k = tam, indice = Valores.size()+1;
        while(band == false){
           valor = (Valores.get(j) + Valores.get(k))%m;
           if(comprobador(valor) == true){
               band = true;  
           }
           Valores.add(valor);
           indice++;
           j++;
           k++;
           
        }
        
        String Matriz [][] = new String [Valores.size()][4];
        int cont = 0, cont1 = tam;
        for(int i = 0; i < Valores.size();i++){
            Matriz[i][0] = "X"+String.valueOf(i);
            if(i >= tam ){
                Matriz[i][2] = "("+String.valueOf(Valores.get(cont))+ "+ " + String.valueOf(Valores.get(cont1)) +") mod "+String.valueOf(m);
                Matriz[i][1] = "(X"+String.valueOf(cont)+"+ X" +String.valueOf(cont1)+") mod m "; 
                cont++;
                cont1++;
            }
            Matriz[i][3] = String.valueOf(Valores.get(i));
            
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Matriz,
            new String [] {
                "Iteración", "Expresión", "Expresión reemplazada", "Resultado"
            }
        ));
        
        
        
    }//GEN-LAST:event_jButton_aditivoActionPerformed
    
    public boolean comprobador(int valor_actual){
        boolean bandera = false;
        for(int i = 0; i < Valores.size();i++){
            if(Valores.get(i) == valor_actual){
                bandera = true;
            } 
        } 
        return bandera;
    }
    
    
    private void jButton_aditivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aditivo1ActionPerformed
        int interaciones = 0, cont_semilla = 0,valor_semilla = 0, valor_resultado;
        String semilla;
        semilla = jTextField_X0.getText();
         try {
                interaciones = Integer.parseInt(jTextField_Iteraciones.getText());
            } 
            catch (NumberFormatException e) {
               JOptionPane.showMessageDialog(null,"Error, ingrese la cantidad de iteraciones.");
            }
         if (semilla.length() != 4){
             JOptionPane.showMessageDialog(null,"Error, solo se aceptan números de 4 dígitos");
         }
         else{
             //cont_semilla = semilla.length();
             try {
               valor_semilla = Integer.parseInt(semilla);
            } 
            catch (NumberFormatException e) {
               JOptionPane.showMessageDialog(null,"Error, debe introducir digitos numericos");
            }
         }
         Valores_Semillas.add(valor_semilla);
         valor_resultado = (int) pow(valor_semilla,2);
         Valores_Cuadrado.add(valor_resultado);
         String nueva_semilla;
         int longitud_resultado;
         for(int i = 0; i < interaciones; i++){
             nueva_semilla = null;
             longitud_resultado = Integer.toString(Valores_Cuadrado.get(i)).length();
             
             if( longitud_resultado == 7){
                 nueva_semilla = String.valueOf(Valores_Cuadrado.get(i));
                 Valores_Semillas.add(Integer.parseInt(nueva_semilla.substring(1,5)));
             }
             if(longitud_resultado == 8){
                nueva_semilla = String.valueOf(Valores_Cuadrado.get(i));
                Valores_Semillas.add(Integer.parseInt(nueva_semilla.substring(2,6)));
             }
             //JOptionPane.showMessageDialog(null,"Cadena semilla: " + nueva_semilla);
             //JOptionPane.showMessageDialog(null,"Semilla " + Valores_Semillas.get(i));
             Valores_Cuadrado.add((int) pow(Valores_Semillas.get(i+1),2));
             
         }
         
        Integer Matriz_2 [][] = new Integer [Valores_Cuadrado.size()][3];
        
        for(int i = 0; i < Valores_Cuadrado.size() ;i++){
            Matriz_2[i][0] = i;
            Matriz_2[i][1] = Valores_Semillas.get(i);
            Matriz_2[i][2] = Valores_Cuadrado.get(i);
        }
        jTable_cuadrado_medio.setModel(new javax.swing.table.DefaultTableModel(
            Matriz_2,
            new String [] {
                "Iteracion", "Semilla", "Resultado"
            }
        ));
        
        
        
        
        
        
    }//GEN-LAST:event_jButton_aditivo1ActionPerformed

    private void jTextField_IteracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IteracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IteracionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Valores_Semillas.clear();
        Valores_Cuadrado.clear();
        jTextField_X0.setText(null);
        jTextField_Iteraciones.setText(null);
        jTable_cuadrado_medio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
            },
            new String [] {
                "Iteracion", "Semilla", "Resultado"
            }
        ));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimpiarActionPerformed
        jTextField_m.setEditable(true);
        jTextField_X_1.setEditable(true);
        Valores.clear();
        jTextField_X_1.setText(null);
        /*jTextField_X_2.setText(null);
        jTextField_X_3.setText(null);
        jTextField_X_4.setText(null);
        jTextField_m.setText(null);*/
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
            },
            new String [] {
                "Iteración", "Expresión", "Expresión reemplazada", "Resultado"
            }
        ));
        
    }//GEN-LAST:event_jButton_LimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String X1 = jTextField_X_1.getText();
        try {
                Valores.add(Integer.parseInt(X1));
            } 
            catch (NumberFormatException e) {
               JOptionPane.showMessageDialog(null,"Error con los valores introducidos");
            }
        String Matriz [][] = new String [Valores.size()][4];
        for(int i = 0; i < Valores.size();i++){
            Matriz[i][0] = "X"+String.valueOf(i);
            Matriz[i][3] = String.valueOf(Valores.get(i));
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Matriz,
            new String [] {
                "Iteración", "Expresión", "Expresión reemplazada", "Resultado"
            }
        ));
        
        jTextField_X_1.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Limpiar;
    private javax.swing.JButton jButton_aditivo;
    private javax.swing.JButton jButton_aditivo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_cuadrado_medio;
    private javax.swing.JTextField jTextField_Iteraciones;
    private javax.swing.JTextField jTextField_X0;
    private javax.swing.JTextField jTextField_X_1;
    private javax.swing.JTextField jTextField_m;
    // End of variables declaration//GEN-END:variables
}
